<a name="inicio"></a>

<div id="cabezote">

	<div class="left">

		<div class="col" style="padding-top:0px; padding-left: 30px;">

			<a href="/es/index.php"><img src="/imagenes/logo.png" width="253px" height="106px" alt="" /></a>

		</div>

	</div>

	<div class="right">

		<div id="menuSuperior">

			<ul class"nivel1">

				<li><a href="/index.php">Inicio</a></li>

				<li><a href="/es/conozcanos.php">Con&oacute;zcanos</a></li>
				
				<li><a href="/es/preguntasFrecuentes/generales.php">FAQ</a></li>
				
				<li><a href="/es/pedidos.php"><strong>Haga su Pedido</strong></a></li>

				<li><a href="/es/contactenos.php">Cont&aacute;ctenos</a></li>

			</ul>

		</div>

	</div>

</div>