		<link href="/css/estilos.css" rel="stylesheet" type="text/css" media="screen" />
		<link href="/css/lightbox.css" rel="stylesheet" type="text/css" media="screen" />
		<script src="/js/prototype.js" type="text/javascript"></script>
		<script src="/js/scriptaculous.js?load=effects" type="text/javascript"></script>
		<script src="/js/DataValidation.js" type="text/javascript"></script>
		<script src="/js/verificacionErrores.js" type="text/javascript"></script>
		<script src="/js/lightbox.js" type="text/javascript"></script>
		<script src="/js/flashobject.js" type="text/javascript"></script>
