<div id="subMenu">
	<ul class="nivel1">
		<li class="listadoSubmenu"><a href="/es/productos/portafoliosDuplicadosDivisiones/portafolios.php">Portafolios</a></li>
		<li class="listadoSubmenu"><a href="/es/productos/portafoliosDuplicadosDivisiones/divisiones.php">Divisiones</a></li>
		<li class="listadoSubmenu"><a href="/es/productos/portafoliosDuplicadosDivisiones/duplicados.php">Duplicados</a></li>
	</ul>
</div>