<div id="subMenu">
	<ul class="nivel1">
		<li class="listadoSubmenu"><a href="/es/preguntasFrecuentes/generales.php">Generales</a></li>
		<li class="listadoSubmenu"><a href="/es/preguntasFrecuentes/bindingCase.php">Sobre binding cases</a></li>
		<li class="listadoSubmenu"><a href="/es/preguntasFrecuentes/letterFile.php">Sobre letter files</a></li>
		<li class="listadoSubmenu"><a href="/es/preguntasFrecuentes/portafoliosDuplicadosDivisiones.php">Sobre portafolios, duplicados y divisiones</a></li>
		<li class="listadoSubmenu"><a href="/es/preguntasFrecuentes/foldersExpandibles.php">Sobre folders expandibles</a></li>
		<li class="listadoSubmenu"><a href="/es/preguntasFrecuentes/articulosPromocionales.php">Sobre art&iacute;culos promocionales</a></li>
		<li class="listadoSubmenu"><a href="/es/preguntasFrecuentes/portadores.php">Sobre los portadores</a></li>
	</ul>
</div>